"""create restaurant tables

Revision ID: 93d7227075cb
Revises: 
Create Date: 2026-08-22 13:25:52.192381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '93d7227075cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu_items', 'name',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('menu_items', 'category',
               existing_type=mysql.ENUM('starter', 'main_course', 'dessert', 'drinks'),
               type_=sa.Enum('STARTER', 'MAIN_COURSE', 'DESSERT', 'DRINKS', name='foodcategory'),
               existing_nullable=False)
    op.alter_column('menu_items', 'is_available',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.drop_column('menu_items', 'created_at')
    op.add_column('order_items', sa.Column('unit_price', sa.Float(), nullable=False))
    op.drop_column('order_items', 'price_at_order')
    op.alter_column('orders', 'status',
               existing_type=mysql.ENUM('pending', 'preparing', 'out_for_delivery', 'delivered'),
               type_=sa.Enum('PENDING', 'PREPARING', 'OUT_FOR_DELIVERY', 'DELIVERED', name='orderstatus'),
               existing_nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.ENUM('admin', 'customer'),
               type_=sa.Enum('ADMIN', 'CUSTOMER', name='userrole'),
               existing_nullable=False)
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'CUSTOMER', name='userrole'),
               type_=mysql.ENUM('admin', 'customer'),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('orders', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.Enum('PENDING', 'PREPARING', 'OUT_FOR_DELIVERY', 'DELIVERED', name='orderstatus'),
               type_=mysql.ENUM('pending', 'preparing', 'out_for_delivery', 'delivered'),
               existing_nullable=False)
    op.add_column('order_items', sa.Column('price_at_order', mysql.FLOAT(), nullable=False))
    op.drop_column('order_items', 'unit_price')
    op.add_column('menu_items', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.alter_column('menu_items', 'is_available',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('menu_items', 'category',
               existing_type=sa.Enum('STARTER', 'MAIN_COURSE', 'DESSERT', 'DRINKS', name='foodcategory'),
               type_=mysql.ENUM('starter', 'main_course', 'dessert', 'drinks'),
               existing_nullable=False)
    op.alter_column('menu_items', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
    # ### end Alembic commands ###
